### ISSUE TITLE
Re-enable the prefix commands 

### ISSUE THREAD

**Issue by thenewgessiko** [moonstar-x/discord-tts-bot#85] opened 2023-01-04 19:11 UTC
Hi moonstar-x, I wanted to ask if you could tell me if it is possible to re-enable prefixes on a tts bot started on your tts bot discord project that I got on github. It's possible?

**Comment by thenewgessiko** [comment] 2023-01-04 21:05
Also because many cannot immediately hear the message reproduced by the bot, and it would be convenient to put them back, or if it is not possible to make the bot say the message both in the voice chat and in the text so that if it is not listened to can also read it.

**Comment by moonstar-x** [comment] 2023-01-05 22:00
Hi there, I will try to work on this during the following weeks.

However, I'm gonna close this issue because it is a duplicate of #79.

**Closed by moonstar-x** 2023-01-05 22:01 UTC
Labels: Type: Feature Request

**Comment by thenewgessiko** [comment] 2023-01-11 07:02
Keep me updated because as soon as it comes out I'll update it immediately
...

Il Gio 5 Gen 2023, 23:01 moonstar-x ***@***.***> ha scritto:
